// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // await Firebase.initializeApp(
  //   options: DefaultFirebaseOptions.currentPlatform,
  // );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSGNmRDs719uUPyn6P7FOJDYT3k7aFU_Y',
    appId: '1:190236807348:web:511d574a5ddd6a6f6647e1',
    messagingSenderId: '190236807348',
    projectId: 'limebadge',
    authDomain: 'limebadge.firebaseapp.com',
    storageBucket: 'limebadge.appspot.com',
    measurementId: 'G-QHQN6L5F0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3sVXLZuP63pOFxe7FESvoce8K4mV5BDU',
    appId: '1:190236807348:android:353f13be993b5a096647e1',
    messagingSenderId: '190236807348',
    projectId: 'limebadge',
    storageBucket: 'limebadge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBty5TnBfWfTqkGKYiT0imc92aGTG29ZQg',
    appId: '1:190236807348:ios:3e0d79b9629872176647e1',
    messagingSenderId: '190236807348',
    projectId: 'limebadge',
    storageBucket: 'limebadge.appspot.com',
    iosBundleId: 'com.google.firebase.present.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBty5TnBfWfTqkGKYiT0imc92aGTG29ZQg',
    appId: '1:190236807348:ios:171e74eb154024536647e1',
    messagingSenderId: '190236807348',
    projectId: 'limebadge',
    storageBucket: 'limebadge.appspot.com',
    iosBundleId: 'com.google.firebase.present.demo.RunnerTests',
  );
}
